// <auto-generated />
using System;
using APBD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APBD.Migrations
{
    [DbContext(typeof(PrescriptionDbContext))]
    [Migration("20200518094557_AddPrescription")]
    partial class AddPrescription
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APBD.Models.Trener", b =>
                {
                    b.Property<int>("IdTrener")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTrener");

                    b.ToTable("Treners");
                });

            modelBuilder.Entity("APBD.Models.Program", b =>
                {
                    b.Property<int>("IdTrener")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTrener")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTrener")
                        .HasColumnType("int");

                    b.Property<int>("IdKlient")
                        .HasColumnType("int");

                    b.HasKey("IdTrener");

                    b.HasIndex("IdTrener");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("APBD.Models.Program", b =>
                {
                    b.HasOne("APBD.Models.Trener", "Trener")
                        .WithMany("Programs")
                        .HasForeignKey("IdTrener");
                });
#pragma warning restore 612, 618
        }
    }
}
